name: social_media_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  provider: ^6.1.2
  # Firebase auth, firestore, storage, and connection.
  firebase_core: ^2.19.0
  cloud_firestore: ^4.12.0
  firebase_storage: ^11.7.1
  firebase_auth: ^4.19.1
# for chat messaging
  flutter_firebase_chat_core: ^1.6.7
  flutter_chat_ui: ^1.6.12
  flutter_chat_types: ^3.6.2
  # for nav bar
  persistent_bottom_nav_bar: ^5.0.2

  # image uploader (eventually)
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/test.jpg
