// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYPfLkil0icx0dT-M3vcdcEo5qRt5Nx_M',
    appId: '1:218396810375:web:b5462fb32c0100518cac22',
    messagingSenderId: '218396810375',
    projectId: 'social-media-app-988e8',
    authDomain: 'social-media-app-988e8.firebaseapp.com',
    databaseURL: 'https://social-media-app-988e8-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-app-988e8.appspot.com',
    measurementId: 'G-DFVZ9CDTXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkKo2UDNGSoqTtHmqz7EYWvarB7usmgQA',
    appId: '1:218396810375:android:4cbd3eda55b586958cac22',
    messagingSenderId: '218396810375',
    projectId: 'social-media-app-988e8',
    databaseURL: 'https://social-media-app-988e8-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-app-988e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM8gEdKGuVAfMQZ1CZGRL9yAyJ4vpqYuI',
    appId: '1:218396810375:ios:cf3e962dba0dde8b8cac22',
    messagingSenderId: '218396810375',
    projectId: 'social-media-app-988e8',
    databaseURL: 'https://social-media-app-988e8-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-app-988e8.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM8gEdKGuVAfMQZ1CZGRL9yAyJ4vpqYuI',
    appId: '1:218396810375:ios:19eed91f163ae05d8cac22',
    messagingSenderId: '218396810375',
    projectId: 'social-media-app-988e8',
    databaseURL: 'https://social-media-app-988e8-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-app-988e8.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
